#!/usr/bin/env bash
#displays bad luck from china for the 4th loop, bad luck from japan for the 9th loop, bad luck from Italy for the 17th loop
x=1
while [ $x -le 20 ]
do
	echo "$x"

	case $x in
	4)
		echo 'bad luck from China'
		;;
	9)
		echo 'bad luck from Japan'
		;;
	17)
		echo 'bad luck from Italy'
	esac
	x=$((x + 1))
done
